import "./globals.css";
import TopLoader from "nextjs-toploader";

import { ContextProvider } from "@/components/context-provider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<{
  children: React.ReactNode;
}> = ({ children }) => {

  return (
    <html lang="en" className="dark">
      <body>
        <ContextProvider>
          <TopLoader color="hsl(240 5.9% 10%)" />
          <div className="container">
            {children}
          </div>
        </ContextProvider>
      </body>
    </html>
  )
};

export default RootLayout;