import "./globals.css";
import TopLoader from "nextjs-toploader";

import { ContextProvider } from "@/components/context-provider";
import type { Metadata } from "next";
import { Header } from "@/components/header";
import { SideMenu } from "@/components/side-menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <ContextProvider>
          <TopLoader color="hsl(240, 5.9%, 50%)" showSpinner={false} />
          <Header />
          <div className="flex gap-2 items-start container min-h-[40rem]">
            <SideMenu />
            <div className="py-8">{children}</div>
          </div>
        </ContextProvider>
      </body>
    </html>
  );
};

export default RootLayout;
